/* tslint:disable */

/* eslint-disable */

/**
 * Platform.Workflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import { DatabaseType } from './database-type';

/**
 *
 * @export
 * @interface DatabaseMetadata
 */
export interface DatabaseMetadata {
  /**
   *
   * @type {DatabaseType}
   * @memberof DatabaseMetadata
   */
  databaseType?: DatabaseType;
  /**
   *
   * @type {string}
   * @memberof DatabaseMetadata
   */
  host?: string | null;
  /**
   *
   * @type {string}
   * @memberof DatabaseMetadata
   */
  port?: string | null;
  /**
   *
   * @type {string}
   * @memberof DatabaseMetadata
   */
  username?: string | null;
  /**
   *
   * @type {string}
   * @memberof DatabaseMetadata
   */
  password?: string | null;
  /**
   *
   * @type {string}
   * @memberof DatabaseMetadata
   */
  targettedDatabaseName?: string | null;
}
