/* tslint:disable */
/* eslint-disable */
/**
 * Platform.Workflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */

export const DatabaseType = {
  MsSql: 'MsSql',
  Postgres: 'Postgres',
} as const;

export type DatabaseType = (typeof DatabaseType)[keyof typeof DatabaseType];
