/* tslint:disable */

/* eslint-disable */

/**
 * Platform.Auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import { CredentialProvider } from './credential-provider';

/**
 *
 * @export
 * @interface LoginRequest
 */
export interface LoginRequest {
  /**
   *
   * @type {CredentialProvider}
   * @memberof LoginRequest
   */
  provider: CredentialProvider;
  /**
   * OAuth Provider이 보내주는 인가 코드입니다.
   * @type {string}
   * @memberof LoginRequest
   */
  authenticationCode: string;
}
