/* tslint:disable */

/* eslint-disable */

/**
 * Platform.Auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import { CredentialProvider } from './credential-provider';

/**
 *
 * @export
 * @interface SignUpRequest
 */
export interface SignUpRequest {
  /**
   * User Nickname
   * @type {string}
   * @memberof SignUpRequest
   */
  name?: string | null;
  /**
   * User Email
   * @type {string}
   * @memberof SignUpRequest
   */
  email?: string | null;
  /**
   * Profile Image URL(Can be NULL)
   * @type {string}
   * @memberof SignUpRequest
   */
  profileImageUrl?: string | null;
  /**
   * 로그인 API에서 받은 Join Token입니다.
   * @type {string}
   * @memberof SignUpRequest
   */
  joinToken?: string | null;
  /**
   *
   * @type {CredentialProvider}
   * @memberof SignUpRequest
   */
  credentialProvider?: CredentialProvider;
}
