/* tslint:disable */

/* eslint-disable */

/**
 * Platform.Auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import { LoginResult } from './login-result';

/**
 *
 * @export
 * @interface TokenResponse
 */
export interface TokenResponse {
  /**
   *
   * @type {LoginResult}
   * @memberof TokenResponse
   */
  loginResult: LoginResult;
  /**
   * Access Token, expires in an hour.
   * @type {string}
   * @memberof TokenResponse
   */
  token: string;
  /**
   * Refresh Token, expires in 30 days.
   * @type {string}
   * @memberof TokenResponse
   */
  refreshToken?: string | null;
}
